select * from `cellavita`.`donors`;
select * from `cellavita`.`exams`;
select * from `cellavita`.`stages`;
select * from `cellavita`.`travels`;
select * from `cellavita`.`cultures`;
select * from `cellavita`.`vaccines`;
select * from `cellavita`.`addresses`;
select * from `cellavita`.`telephones`;
alter table `cellavita`.`cultures` add index `fk_cultures_cells1_idx` (`donor_id` ASC, `cell_id` ASC);
select (max(`donor_id`)+1) as `next_id` from `cellavita`.`donors`;
select (max(`address_id`)+1) as `next_donor_address_id` from `cellavita`.`addresses` where `donor_id`= 2;
select (max(`phone_id`)+1) as `next_donor_telephone_id` from `cellavita`.`telephones` where `donor_id`= 1;
select * from `cellavita`.`users`;